### ISSUE TITLE
Adjusting for Multiple comparisons 

### ISSUE THREAD

**Issue by SannaAb** [yiluheihei/microbiomeMarker#41]
Hi, 

Thank you for a great package. I have been trying to perform multiple correction on the lefse output using the correct parameter for lefse, but it seems that setting correct to "0","1","2" does not change the reported P-adjusted values, they are still the same as the P-values. 

Thanks for your help,

**Comment by jaspkau** [comment]
Hi,

I am also facing the same problem. Did you find any solution for this?

**Comment by yiluheihei** [comment]
@SannaAb @jaspkau  I'm very sorry for the delayed response. Does your problem solved? If not, I will try to solve it as soon as possible.

**Comment by SannaAb** [comment]
Hi, I have not found a solution to this yet.

**Comment by yiluheihei** [comment]
@SannaAb @jaspkau 

 After reread the source code of lefse, I realized what the problem is. The "correction" here is a bit misleading. The `correct` is only just affect the cutoff of p values for multiple tests. While it is set to 1 or 2, the cutoff of p value is changed (increased) as shown in the source code, which means that the p values more permissive for multiple tests. By default, LEfSe will conservatively treat them as a single bulk test, hence more strict. Thus, the p values are the same no matter the `correct` is set as 0, 1 or 2. The `correct` only affect the number of significant features other than p values.

- 0 means no correction
- 1 means correction for multiple independent tests
- 2 means correction for multiple dependent tests.



```r
if (correct != 0) {
      wilcoxon_cutoff <- ifelse(
        correct == 2,
        wilcoxon_cutoff * subcls1_n * subcls2_n,
        1 - (1 - wilcoxon_cutoff)^(subcls1_n * subcls2_n)
      )
}
```

Sorry for the misleading, and I have change the para `correct` to `strict` in the new version of **microbiomeMarker**. Hope this helps for you.

Please feel free to let me know if you have any further questions. If you think this project is helpful to you, you can give this project a star ⭐.

Thanks for your interested in microbiomeMarker.
