### ISSUE TITLE
plot_cladogram(): Mismatch between marker legend and plot labels

### ISSUE THREAD

**Issue by sn0001** [yiluheihei/microbiomeMarker#42]
Thank you for this great package! Trying `plot_cladogram()` with many makers, I noticed that the labels of the marker legend do not agree with those in the plot. Specifically, this happens when there are more markers than latin letters and double letter combinations are used.

Minimum reproducible example:
```
data("spontaneous_colitis")
mm_lefse <- run_lefse(
    kostic_crc,
    wilcoxon_cutoff = 0.01,
    class = "DIAGNOSIS",
    kw_cutoff = 0.01,
    multicls_strat = TRUE,
    lda_cutoff = 3
)
plot_cladogram(mm_lefse, color = c("blue", "red"), marker_legend_param = list(ncol = 2))
```
In the upper left of the cladogram, you will notice a red "Tumor"-related group with letter codes `aa` and `j`. The latter do not belong to "Tumor" markers.

**Comment by yiluheihei** [comment]
@sn0001  I'm very sorry for the delay reply. The example data `spontaneous_colitis` was from galaxy lefse demo, and the data has been summarized to a taxonomic level (e.g. seprated by |). In order to test the accuracy and reliability of the lefse algorithm implemented in microbiomeMarker, this data is only used for test the accuracy of lefse results.

In the current version of microbiomeMarker, the analysis is begin from the taxa table rather than the summarized taxa table, which means that summarized data like `spontaneous_colitis` is not supported in the current release version. I'm very sorry for the confusion cased by this data, and maybe I should remove this example data.

**Comment by sn0001** [comment]
@yiluheihei Thank you for your reply. I am running into the described error with my own data, too. How do I have to prepare my phyloseq data for microbiomeMarker to avoid the marker legend mismatch error?

**Comment by yiluheihei** [comment]
Could you provide a reproducible example?

**Comment by sn0001** [comment]
@yiluheihei Of course! Please unzip the attached [phyloseq object data](https://github.com/yiluheihei/microbiomeMarker/files/7595365/phyloseq.zip) and use them along with the code below:

```
library(microbiomeMarker)
set.seed(123)
ps <- readRDS("phyloseq.rds")
mm <- run_lefse(ps, group = "Grouping")
plot_cladogram(mm, color = c("blue", "green", "red"))
```
The result should look as in the screenshot below. Note that marker “ag” belongs to Group_8 according to the cladogram, but to Group_1 according to the legend.

![screenshot](https://user-images.githubusercontent.com/26900623/143233400-c652932d-c848-4bed-a378-6b38572582ca.png)

**Comment by yiluheihei** [comment]
@sn0001 The issue was fixed. You can reinstall the package from github and try again. Thanks your feedback again.

**Comment by sn0001** [comment]
@yiluheihei Thanks a lot!
